databaseChangeLog:
  - logicalFilePath: 20230712-01-create-table-register-limit-config.yaml
  - changeSet:
      id: 20230712-1
      author: TajaddinGanjali
      changes:
        - createTable:
            columns:
              - column:
                  constraints:
                    nullable: false
                    primaryKey: true
                  name: ID
                  type: NUMBER(19, 0)
              - column:
                  constraints:
                    nullable: false
                  name: CREATED_DATE
                  remarks: inserted row date
                  type: TIMESTAMP(6)
              - column:
                  name: UPDATED_DATE
                  remarks: updated row date
                  type: TIMESTAMP(6)
              - column:
                  constraints:
                    nullable: false
                  name: STATE
                  remarks: 0 - DELETED; 1 - ACTIVE;  2 - UPDATED; 3 - DEACTIVE
                  type: NUMBER(1, 0)
              - column:
                  name: ATTEMPT_COUNT
                  constraints:
                    nullable: false
                  remarks: Attempt count
                  type: NUMBER(3, 0)
              - column:
                  name: LOCK_TIME
                  constraints:
                    nullable: false
                  remarks: Lock time in minute
                  type: NUMBER(4, 0)
              - column:
                  name: SERVICE
                  constraints:
                    nullable: false
                  remarks: Service type to apply limit
                  type: NUMBER(2,0)
            remarks: Limit configuration for Registration
            tableName: REGISTER_LIMIT_CONFIG

  - changeSet:
      id: 20230712-2
      author: TajaddinGanjali
      changes:
        - createSequence:
            maxValue: 9999999999999999999999999999
            sequenceName: REGISTER_LIMIT_CONFIG_SEQ
            startValue: 1

  - changeSet:
      id: 20230712-3
      author: TajaddinGanjali
      changes:
        - sqlFile:
            comment: add check constraint
            splitStatements: true
            path: db/changelog/v-3.0/register-limit-config/sql/20230712-01-add-constraint-register-limit-config.sql