INSERT INTO REGISTER_LIMIT_CONFIG
(ID, CREATED_DATE, UPDATED_DATE, STATE, ATTEMPT_COUNT, LOCK_TIME, SERVICE)
VALUES(1, SYSDATE, NULL, 1, 3, 1440, 2);
INSERT INTO REGISTER_LIMIT_CONFIG
(ID, CREATED_DATE, UPDATED_DATE, STATE, ATTEMPT_COUNT, LOCK_TIME, SERVICE)
VALUES(2, SYSDATE, NULL, 1, 3, 1440, 3);
